### ISSUE TITLE
OMERO-web startup issues

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/devspace#32]
Currently looking into orca-3:42888's web startup failures (e.g. in build 8):

```
Apr 17 12:28:03 a5a0365505ae systemd[1]: Failed to start OMERO.web.
Apr 17 12:28:03 a5a0365505ae systemd[1]: Unit omero-web.service entered failed state.
Apr 17 12:28:03 a5a0365505ae systemd[1]: omero-web.service failed.
[root@a5a0365505ae tmp]# cat /etc/systemd/system/omero-web.service
[Unit]
Description=OMERO.web

[Service]
User=omero
Type=forking
PIDFile=/home/omero/OMERO.server/var/django.pid
Restart=on-failure
RestartSec=10
Environment="VENVDIR=/home/omero/omero-virtualenv" "BINDIR=/home/omero/OMERO.server/bin"
ExecStart=/usr/bin/bash -c "source $VENVDIR/bin/activate; $BINDIR/omero web start"
ExecStop=/usr/bin/bash -c "source $VENVDIR/bin/activate; $BINDIR/omero web stop"
Restart=/usr/bin/bash -c "source $VENVDIR/bin/activate; $BINDIR/omero web restart"

[Install]
WantedBy=multi-user.target[root@a5a0365505ae tmp]# su - omero
Last login: Sun Apr 17 12:27:15 UTC 2016
-bash-4.2$ VENVDIR=/home/omero/omero-virtualenv/
-bash-4.2$ BINDIR=/home/omero/OMERO.server/bin/
-bash-4.2$ bash -c "source $VENVDIR/bin/activate; $BINDIR/omero web start"
Copying '/home/omero/OMERO.server/lib/python/omeroweb/feedback/static/feedback/css/layout.css'
Traceback (most recent call last):
  File "manage.py", line 56, in <module>
    execute_from_command_line(sys.argv)
  File "/home/omero/omero-virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/omero/omero-virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/omero/omero-virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/omero/omero-virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/omero/omero-virtualenv/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/home/omero/omero-virtualenv/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 107, in collect
    handler(path, prefixed_path, storage)
  File "/home/omero/omero-virtualenv/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 315, in copy_file
    self.storage.save(prefixed_path, source_file)
  File "/home/omero/omero-virtualenv/lib/python2.7/site-packages/django/core/files/storage.py", line 63, in save
    name = self._save(name, content)
  File "/home/omero/omero-virtualenv/lib/python2.7/site-packages/django/core/files/storage.py", line 222, in _save
    os.makedirs(directory)
  File "/home/omero/omero-virtualenv/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/home/omero/omero-virtualenv/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/omero/static/web/feedback'
-bash-4.2$ OMERO.server//bin/omero config get
omero.web.application_server=wsgi-tcp
omero.web.application_server.host=0.0.0.0
omero.web.application_server.max_requests=0
omero.web.application_server.port=4080
omero.web.caches={"default": {"BACKEND": "redis_cache.RedisCache","LOCATION": "redis:6379"}}
omero.web.prefix=/web
omero.web.server_list=[["omero", 4064, "omero"], ["slave", 4064, "slave"]]
omero.web.session_engine=django.contrib.sessions.backends.cache
omero.web.static_root=/home/omero/static/web
omero.web.static_url=/web/static/
```

```
drwxr-xr-x  3 root  root  4096 Apr  8 21:37 static
```

As a workaround I've made `static` and `static/web` world-writeable.

**Comment by aleksandra-tarkowska** [comment]
https://trello.com/c/K0AUE15q/1782-beluga-docker-compose-and-permissions

**Comment by aleksandra-tarkowska** [comment]
how about

```
CMD chown -R nginx:nginx /home/omero/static/web
```

**Comment by joshmoore** [comment]
Added, but the container is still exiting. I'll ping you later to find out how to recover.

**Comment by joshmoore** [comment]
@aleksandra-tarkowska : how was it that you fixed this?

**Comment by aleksandra-tarkowska** [comment]
Chmod 777 -R /home/omero/static

**Comment by joshmoore** [comment]
Manually after startup?

**Comment by aleksandra-tarkowska** [comment]
This is now handled on startup

https://github.com/openmicroscopy/devspace/pull/31/files#diff-7cae68e17c6e252cfd72e0e14b0a9a66R2

**Comment by joshmoore** [comment]
:+1:
