### ISSUE TITLE
authenticity of host 'github.com can't be established

### ISSUE THREAD

**Issue by aleksandra-tarkowska** [openmicroscopy/devspace#38]
When startin fresh new devspace there are no `./ssh/known_hosts`. This cause push build failure

```
+ /home/omero/.local/bin/scc merge develop --no-ask --reset -S no-error --push develop/merge/trigger
2016-04-18 17:28:54,440 [   scc.merge] INFO  Merging Pull Request(s) based on develop
2016-04-18 17:28:54,440 [   scc.merge] INFO  Including Pull Request(s) opened by any public member of the organization
2016-04-18 17:28:54,440 [   scc.merge] INFO  Including Pull Request(s) labelled as include
2016-04-18 17:28:54,440 [   scc.merge] INFO  Excluding Pull Request(s) labelled as exclude or breaking
2016-04-18 17:28:54,440 [   scc.merge] INFO  Excluding Pull Request(s) with either error or failure status
2016-04-18 17:30:00,271 [   scc.merge] INFO  Repository: openmicroscopy/bioformats
2016-04-18 17:30:00,271 [   scc.merge] INFO  Excluded PRs:
...
2016-04-18 17:30:00,272 [   scc.merge] INFO  Merged PRs:
...
2016-04-18 17:30:00,273 [   scc.merge] INFO  
Traceback (most recent call last):
  File "/home/omero/.local/lib/python2.7/site-packages/scc/main.py", line 76, in entry_point
    (UpdateSubmodules.NAME, UpdateSubmodules),
  File "/home/omero/.local/lib/python2.7/site-packages/yaclifw/framework.py", line 197, in main
    ns.func(ns)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 2912, in __call__
    self.push(args, self.main_repo)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 1984, in push
    main_repo.rpush(branch_name, remote, force=True)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 1833, in rpush
    self.push_branch(branch_name, remote=full_remote, force=force)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 98, in wrapper
    return func(*args, **kwargs)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 1147, in push_branch
    self.call("git", "push", "-f", remote, name)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 1013, in call
    return self.wrap_call(self.debugWrap, *command, **kwargs)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 1038, in wrap_call
    raise Exception("rc=%s" % rc)
Exception: rc=128
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

This is because:

```
The authenticity of host 'github.com (192.30.252.123)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
```

to solve that problem:

```
$ docker exec -it develop_testice35_1 bash
[root@901eecee7574 linux]# su - omero
-bash-4.2$ cd workspace/BIOFORMATS-push/src/
-bash-4.2$ /home/omero/.local/bin/scc merge develop --no-ask --reset -S no-error --push develop/merge/trigger
...
The authenticity of host 'github.com (192.30.252.123)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
2016-04-18 17:31:25,958 [   scc.merge] INFO  Merged branch pushed to https://github.com/snoopycrimecop/bioformats/tree/develop/merge/trigger
-bash-4.2$
```

**Comment by aleksandra-tarkowska** [comment]
this allows to build BF-push but OMERO-push is still failing with:

```
-bash-4.2$ /home/omero/.local/bin/scc merge develop --no-ask --reset -S no-error --push develop/merge/trigger
2016-04-18 17:49:04,442 [   scc.merge] INFO  Merging Pull Request(s) based on develop
2016-04-18 17:49:04,442 [   scc.merge] INFO  Including Pull Request(s) opened by any public member of the organization
2016-04-18 17:49:04,442 [   scc.merge] INFO  Including Pull Request(s) labelled as include
2016-04-18 17:49:04,442 [   scc.merge] INFO  Excluding Pull Request(s) labelled as exclude or breaking
2016-04-18 17:49:04,442 [   scc.merge] INFO  Excluding Pull Request(s) with either error or failure status
Traceback (most recent call last):
  File "/home/omero/.local/lib/python2.7/site-packages/scc/main.py", line 76, in entry_point
    (UpdateSubmodules.NAME, UpdateSubmodules),
  File "/home/omero/.local/lib/python2.7/site-packages/yaclifw/framework.py", line 197, in main
    ns.func(ns)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 2905, in __call__
    self.merge(args, self.main_repo)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 2935, in merge
    set_commit_status=args.set_commit_status)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 1662, in rmerge
    set_commit_status=set_commit_status)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 1412, in merge
    self.fetch(key)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 1141, in fetch
    self.call("git", "fetch", remote)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 1013, in call
    return self.wrap_call(self.debugWrap, *command, **kwargs)
  File "/home/omero/.local/lib/python2.7/site-packages/scc/git.py", line 1038, in wrap_call
    raise Exception("rc=%s" % rc)
Exception: rc=1
-bash-4.2$
```

**Comment by joshmoore** [comment]
From https://trello.com/c/z5LrlWMy/275-spaces-work:

```
ssh-keyscan github.com >> ~/.ssh/known_hosts
```

**Comment by aleksandra-tarkowska** [comment]
thank you that works ;-)

**Comment by aleksandra-tarkowska** [comment]
looks like too early enthusiasm. I started fresh devspace deployment and having the same problem now

**Comment by yanjunhui2014** [comment]
@joshmoore thank u, it work!

**Comment by Aaron-Penn-Interactive** [comment]
I've been having this problem, but it doesn't ask if I want to continue. It just hangs there. I ran the ssh-keyscan command and I see the entry in the known_hosts file, but I still get the authenticity error. Even restarted my computer to no avail. Any ideas?

**Comment by joshmoore** [comment]
Hi @Aaron-Penn-Interactive,

Hmm.... sounds like there's something else going on here. By my count, you've ok'd the authenticity at last twice but it's still not asking for confirmation which is weird. The only thing I can think of off-hand is if there are different users/machines/contexts by which `known_hosts` somehow changes.

I will note that GitHub itself has improved there docs around this in case there's anything there that might help you:

https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/testing-your-ssh-connection

~Josh

**Comment by SofijaErkin** [comment]
Just typing "yes".

**Comment by assem-khaleel** [comment]
> From https://trello.com/c/z5LrlWMy/275-spaces-work:
> 
> ```
> ssh-keyscan github.com >> ~/.ssh/known_hosts
> ```
Your amazing man , you made my day , thanks a lot

**Comment by mpalenov** [comment]
`ssh-keyscan github.com >> ~/.ssh/known_hosts` just leads to another error

```
npm WARN prepare removing existing node_modules/ before installation
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/kleros/dispute-resolver-interface-contract.git
npm ERR! 
npm ERR! Warning: Permanently added the ECDSA host key for IP address '140.82.121.4' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

**Comment by joshmoore** [comment]
Hi @mpalenov. Sounds like there's more involved in your case. For example, the `ssh-keyscan github.com >> ~/.ssh/known_hosts` should have prevented `npm ERR! Warning: Permanently added the ECDSA host key for IP address '140.82.121.4' to the list of known hosts.` Perhaps it was run as a separate user or in a separate context? Also the error `npm ERR! git@github.com: Permission denied (publickey).` most likely comes from a missing SSH key somewhere. But if you are in an interactive shell, you're right: "Just run `ssh git@github.com` instead" :+1:

**Comment by Lukortech** [comment]
> From https://trello.com/c/z5LrlWMy/275-spaces-work:
> 
> ```
> ssh-keyscan github.com >> ~/.ssh/known_hosts
> ```

Thank you so much for this.
I've been haunted by the error for quite some time.

**Comment by muhammadtayyabrajput** [comment]
> 

it works thanks bro

**Comment by yaylucasf** [comment]
Thank you!
